### PR TITLE
Added more on version control definition

### PR DESCRIPTION
**Pull request by katylee228**
@bontgoy

### CODE REVIEW

**Comment by katylee228** [comment]
@bontgoy I hope that I got the right repository this time...

**Comment by Bontgoy** [comment]
@katylee228 Yup this is the right place!  :shipit: 

In the future wait to merge any pull requests you've tagged me in until I have commented.

Thanks

**Comment by katylee228** [comment]
Hello Tyler,

I got it. Thanks for the kind info. Have a wonderful day.

Best,
Katy

**Comment by Bontgoy** [comment]
🍕

**Pull request merged**
